/* DO NOT EDIT THIS FILE - it is machine generated */
#if (!defined(DBEUG) && !defined(_DEBUG))
#ifndef __APPLE__
#include <jni.h>
#endif
#endif
/* Header for class com_intech_dbcryptor_Cryptor */

#ifndef _Included_SignIdentifierDllHeader
#define _Included_SignIdentifierDllHeader
#ifdef __cplusplus
extern "C" {
#endif

#if (!defined(DBEUG) && !defined(_DEBUG) && !defined(__APPLE__))
	JNIEXPORT jstring JNICALL Java_com_intech_security_neptune_SignTool_getSign
	(JNIEnv *, jobject, jstring, jstring, jstring);


	JNIEXPORT jboolean JNICALL Java_com_intech_security_neptune_SignTool_verifySign
	(JNIEnv *, jobject, jstring, jstring, jstring, jstring);
#endif

#if (defined(WIN32) || defined(_WINDOWS))
	__declspec(dllexport) char* getSign(char* pSrc, char* qid, char* keyEnum);

	__declspec(dllexport) bool verifySign(char* pSignature, char* pSrc, char* qid, char* keyEnum);
#else
	char* getSign(char* pSrc, char* qid, char* keyEnum);
	bool verifySign(char* pSignature, char* pSrc, char* qid, char* keyEnum);
#endif

#ifdef __cplusplus
}
#endif
#endif